### ISSUE TITLE
send patch to mxnet on the CTC operator?

### ISSUE THREAD

**Issue by szha** [HawkAaron/MXNet-CTC#1]
Hi,

Thanks for making the code available. I'm wondering if you'd like to send a patch on the CTC operator and fix the problem.  Also, would you mind describing the changes you made here?

**Comment by szha** [comment]
@JerryZcn This might be of interest to you since you'd like to make the patch too.

**Comment by Jerryzcn** [comment]
there seems to be some bug. getting 
MXNetError: [00:41:00] src/operator/contrib/./warpctc_loss-inl.h:339: Check failed: in_type->at(i) == type || in_type->at(i) == -1 Unsupported data type 0

**Comment by HawkAaron** [comment]
The kernel is the same with WarpCTC, here just add a mxnet operator.

**Comment by szha** [comment]
@HawkAaron would you be interested in collaborating with Jerry?

**Comment by HawkAaron** [comment]
Here I just add a mxnet operator for WarpCTC, the only change is the input data types:
for MXNet CTC, it only accept float32 data type, here I use float32 only for activations, the other three inputs are int32.

**Comment by HawkAaron** [comment]
@szha Yeah, I'd like to fix the CTC problem.

**Comment by Jerryzcn** [comment]
@HawkAaron i see it is using sparse labels

**Comment by Jerryzcn** [comment]
@HawkAaron How do you plan to merge this to mxnet master? @szha should we deprecate ctc_loss in favor of warp_ctc? We also need to make couple changes so that the APIs are compatible with the old gluon API. Specifically, the data type, and the default blank_label.

**Comment by szha** [comment]
ctc_loss was added to port the warp ctc into mxnet code base, so that users don't need to install baidu's code first.

**Comment by Jerryzcn** [comment]
@HawkAaron Do you have a timeline for patching this.

**Comment by HawkAaron** [comment]
There are two ways:
1. replace ctc_loss with this warp-ctc, I can change this binding to make it compatible with the old API.
2. fix the ctc_loss problem

So what's your idea?

**Comment by szha** [comment]
you'd likely find that the code is very much the same since they have the same source. so I've been intending 2. all along.

**Comment by HawkAaron** [comment]
I'll try my best to fix it within this week.

**Comment by szha** [comment]
Thanks. @Jerryzcn and I would be more than glad to help with review
